### ISSUE TITLE
Pas Gabung PPT, Title Ketimpa Nomer

### ISSUE THREAD

**Issue by lguiel** [hanatanjung/muse-processor#5]
Sekarang:
<img width="1029" alt="Screen Shot 2021-01-28 at 20 55 14" src="https://user-images.githubusercontent.com/4798369/106135438-46334880-61ab-11eb-9514-ec85b60fff8c.png">

Harusnya:
<img width="1024" alt="Screen Shot 2021-01-28 at 20 55 33" src="https://user-images.githubusercontent.com/4798369/106135459-4df2ed00-61ab-11eb-8114-f5e9f85dad30.png">

**Comment by hanatanjung** [comment]
https://github.com/hanatanjung/muse-processor/releases/tag/1.0.1
